name: Tutorial submission
description: Submit a tutorial or set of tutorials to Astropy Learn.
title: "[New tutorial]: "
labels: ["content-new", "needs-content-review"]
body:
  - type: markdown
    attributes:
      value: |
        Please complete all of the below information to submit a tutorial or set of tutorials. Thanks in advance for your contribution to Astropy Learn!
  - type: input
    id: tutorial-title
    attributes:
      label: Tutorial title
    validations:
      required: true
  - type: input
    id: authors
    attributes:
      label: Tutorial authors
      description: Include author names, GitHub usernames and ORCID IDs
    validations:
      required: true
  - type: input
    id: requirements
    attributes:
      label: Notebook requirements
      description: Python packages required to run the notebook(s)
    validations:
      required: true
  - type: input
    id: ancillary-files
    attributes:
      label: Attach files
      description: Attach the tutorial notebook(s) and any necessary ancillary files (e.g., data files) needed to run them. Note anything about the files that is not clear from the filenames here.
    validations:
      required: true
  - type: textarea
    id: index-content
    attributes:
      label: Summary (if multiple notebooks)
      description: If you are submitting a set of thematically linked tutorials, please provide a paragraph summarizing all of the notebooks, making clear their sequential order.
    validations:
      required: false
  - type: checkboxes
    id: check-citation
    attributes:
      label: Citation
      description: Check here if you would like the tutorial to be made citable via an upload to [Zenodo](https://zenodo.org/). (If so, be sure to include the authors' ORCID IDs above.)
      options:
        - label: Yes, I would like the tutorial to be made citable via Zenodo.
          required: false
  - type: checkboxes
    id: check-intro
    attributes:
      label: Introduction format
      description: The tutorial(s) contain a complete Introduction cell that includes the tutorial title, author list, learning goals, keywords, companion content if relevant, and a summary - following the format in the [contributing guidelines](https://learn.astropy.org/contributing/).
      options:
        - label: I confirm.
          required: true
  - type: checkboxes
    id: check-guidelines
    attributes:
      label: Contribution guidelines
      description: I am familiar with the Learn Astropy [contributing guidelines](https://learn.astropy.org/contributing/).
      options:
        - label: I confirm.
          required: true
  - type: checkboxes
    id: check-coc
    attributes:
      label: Code of Conduct
      description: I am familiar with the Astropy community [code of conduct](https://github.com/astropy/astropy/blob/main/CODE_OF_CONDUCT.md) and agree to follow it.
      options:
        - label: I confirm.
          required: true
